name: Release DevOps with Docker 3.1

on:
  push:
    branches:
      - main
    paths:
      - 'express-app/**'
      - '.github/workflow/3.1.yaml'

jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./express-app
          file: ./express-app/Dockerfile
          push: true
          tags: tpslr/devops-with-docker-3.1:latest
